CREATE SEQUENCE ACADEMY_COURSE_SEQ
START WITH 10
INCREMENT BY 10
MAXVALUE 9990
NOCYCLE
ORDER;

CREATE SEQUENCE ACADEMY_COURSE_REG_SEQ 
START WITH 101
MAXVALUE 9999
NOCYCLE
ORDER;

/*
SELECT ACADEMY_COURSE_SEQ.CURRVAL
FROM DUAL;

SELECT ACADEMY_COURSE_SEQ.NEXTVAL
FROM DUAL;

SELECT LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'ACADEMY_COURSE_SEQ';
*/